// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsbmrsauwrsdgujzsdkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzYm1yc2F1d3JzZGd1anpzZGt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNTI1NzEsImV4cCI6MjA1OTkyODU3MX0.2FvNCvN7YJajUbPnLTjfwHjgZHoGhzUvDZVg0thWA_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);