
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsbmrsauwrsdgujzsdkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzYm1yc2F1d3JzZGd1anpzZGt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNTI1NzEsImV4cCI6MjA1OTkyODU3MX0.2FvNCvN7YJajUbPnLTjfwHjgZHoGhzUvDZVg0thWA_Y";

// We need to cast the type to any because the generated types don't include our custom tables
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storageKey: 'campus-connect-auth'
    }
  }
);

// Helper function to handle type conversion for Department enum
export const convertToDepartment = (value: string): Department => {
  return value as Department;
};

// Helper function to handle type conversion for Year enum
export const convertToYear = (value: string): Year => {
  return value as Year;
};

// Helper function to parse skills array from string or return empty array
export const parseSkills = (skills: string[] | null | undefined): string[] => {
  if (!skills) return [];
  return skills;
};

// Import types from our type definitions
import { Department, Year } from '@/types';
